const data = [
  {
     "price":6,
     "stock":10,
     "title":"Carrot",
     "image":"img-4.jpg",
     "discount":0,
     "category":"Vegetable",
     "minimum":null,
     "id":1
  },
  {
     "price":12,
     "stock":13,
     "title":"Cabbage",
     "image":"img-1.jpg",
     "discount":5,
     "category":"Vegetable",
     "minimum":null,
     "id":2
  },
  {
     "price":22,
     "stock":21,
     "title":"Strawberry",
     "image":"product-6.jpg",
     "discount":10,
     "category":"Fruit",
     "minimum":null,
     "id":3
  },
  {
     "price":14,
     "stock":14,
     "title":"Orange",
     "image":"product-10.jpg",
     "discount":0,
     "category":"Fruit",
     "minimum":null,
     "id":4
  },
  {
     "price":16,
     "stock":34,
     "title":"Banana",
     "image":"img-5.jpg",
     "discount":4,
     "category":"Fruit",
     "minimum":null,
     "id":5
  },
  {
     "price":32,
     "stock":20,
     "title":"Bell pepper",
     "image":"img-14.jpg",
     "discount":0,
     "category":"Vegetable",
     "minimum":null,
     "id":6
  },
  {
     "price":12,
     "stock":11,
     "title":"Egg",
     "image":"img-15.jpg",
     "discount":12,
     "category":"Dairy & Eggs",
     "minimum":6,
     "id":7
  },
  {
     "price":19,
     "stock":11,
     "title":"Orange Juice",
     "image":"product-15.jpg",
     "discount":12,
     "category":"Beverages",
     "minimum":null,
     "id":8
  }
]

export default data;